// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               v4.25.2
// source: envoy/annotations/deprecation.proto

/* eslint-disable */

export const protobufPackage = "envoy.annotations";
